### ISSUE TITLE
Harden property values against trailing whitespace

### ISSUE THREAD

**Issue by mskopp** [MarcGiffing/bucket4j-spring-boot-starter#102]
I was using bucket4j-spring-boot-starter with a application.properties file with the URL filter defined as

bucket4j.filters[0].url = .* 

but **with a trailing space character**!
The trailing space made ServletRequestFilter#shouldNotFilter never match and it drove me kind of cracy finding the root source... yes.. may everybody have a good laugh on me here :-)
Could you add a `.trim()` to `filterConfig.getUrl()` to make it more fail safe or at least issue a warning in constructor 
`if (!filterConfig.getUrl().equals(filterConfig.getUrl().trim()))`
Thanks

    package com.giffing.bucket4j.spring.boot.starter.filter.servlet;

    public class ServletRequestFilter extends OncePerRequestFilter implements Ordered {
    ...
        protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
		return !request.getRequestURI().matches(filterConfig.getUrl());
	}

**Comment by MarcGiffing** [comment]
I hope this will help...
