### ISSUE TITLE
Add header to response

### ISSUE THREAD

**Issue by pablo-rodr-bio2** [MarcGiffing/bucket4j-spring-boot-starter#105]
I'm trying to use bucket4j to limit the amount of queries to one of my api.
This works, but instead of returning my error message, browser reads a CORS error.
I get that this is because the response from my server doesn't add a Header, so client can't "understand" what the error is.
How can I add a header value to the bucket4j response in order for the client to read it?
I'm asking if this could be achieved through the application.properties file schema.

**Comment by pablo-rodr-bio2** [comment]
for example, I'm trying this at properties but don't get this header attached:

```
bucket4j.filters[0].http-response-headers.error=ResponseEntity.status(HttpStatus.TOO_MANY_REQUESTS).build()

**Comment by MarcGiffing** [comment]
Is your request is to add a header value with a dynamic content, or is a static value enough? Should the header only be added on rate limiting?

**Comment by pablo-rodr-bio2** [comment]
A static value is enough, and yes, the header should only be added on rate limiting. Thanks.

**Comment by MarcGiffing** [comment]
The configuration your're using should work. Can you try to use a simple string for the value of the error.

```properties
bucket4j.filters[0].http-response-headers.KEY=VALUE
bucket4j.filters[0].http-response-headers.HELLO=WORLD
```


![image](https://user-images.githubusercontent.com/3609928/165721240-9c5861b4-d1a3-4428-97ee-820914566b20.png)

**Comment by pablo-rodr-bio2** [comment]
Sorry for answering so late.
I can't provide an example since the app I'm working on is massive. 
But I think the problem is that the 429 status code arrives as a response to a Preflight OPTIONS request, and then the actual request gets a response without a header and then explodes with CORS.
I'm a junior developer so maybe this questions sound extremely naïve, sorry.
This are captions of my network console once I hit the queries limit

![Screenshot from 2022-05-05 13-27-13](https://user-images.githubusercontent.com/53177189/166914321-df44f4e8-dbd9-4ae7-961d-28b9201ff248.png)

![Screenshot from 2022-05-05 13-27-19](https://user-images.githubusercontent.com/53177189/166914342-b8c0926c-0cc4-4bee-bc84-1dc0461f915e.png)

![Screenshot from 2022-05-05 13-27-34](https://user-images.githubusercontent.com/53177189/166914353-98060c05-4f97-4e19-b143-736545a6da2d.png)

Any tip would be awesome. Thanks.

**Comment by pablo-rodr-bio2** [comment]
I finally resolved this issue on my end (regarding pre-fetching)
Thank you very much for your attention.
