### ISSUE TITLE
ZuulRateLimitFilter uses startsWith() in shouldFilter method

### ISSUE THREAD

**Issue by Sa1to** [MarcGiffing/bucket4j-spring-boot-starter#11]
Because of that regex can not be used as url pattern when using zuul filter method. I suggest to replace it wiht matches().
https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/d2ce5450fe54f6e634c9d6433ed36d52521862b1/bucket4j-spring-boot-starter/src/main/java/com/giffing/bucket4j/spring/boot/starter/zuul/ZuulRateLimitFilter.java#L71

**Comment by MarcGiffing** [comment]
Thanks!
