### ISSUE TITLE
The starter seems not to work with spring boot 2.7

### ISSUE THREAD

**Issue by Bad-Pop** [MarcGiffing/bucket4j-spring-boot-starter#111]
I am developing a personal project with spring boot in version 2.7.

In order to preserve the performance of my application and to avoid taking too much scraping at once I want to set up a rate limiter.

So I followed the tutorial of baeldung to integrate bucket4j to my application. Bucket4j and the spring boot starter do the job perfectly with caffein, at least according to the different documentations I could read.

Unfortunately once integrated to my application bucket4j just doesn't work with my version of spring boot.

In your opinion, is it really the spring boot version that causes the problem, and if so, how to solve it?

Thanks a lot

**Comment by MarcGiffing** [comment]
Please try version 0.7.x if released.
