### ISSUE TITLE
Redis TTL does not work

### ISSUE THREAD

**Issue by JakobStadlhuber** [MarcGiffing/bucket4j-spring-boot-starter#116]
I use redis as a cache but I can't configure TTL on the redis level. I think it is because the naming in redis is different to what I configured it:

some of the Bucket4j configs: 

```
bucket4j.enabled=true
bucket4j.cache-to-use=redis
bucket4j.filters[0].cache-name=bucket4j
bucket4j.filters[0].url=.*
bucket4j.filters[0].http-response-body={ "message": "Too many requests" }
#bucket4j.filters[0].rate-limits[0].expression=getRemoteAddr()
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=2
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=120
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=seconds
bucket4j.filters[0].rate-limits[0].bandwidths[1].capacity=50
bucket4j.filters[0].rate-limits[0].bandwidths[1].time=24
bucket4j.filters[0].rate-limits[0].bandwidths[1].unit=hours
...
spring.cache.cache-names=bucket4j
```

Redis: 
<img width="465" alt="Bildschirmfoto 2022-07-15 um 19 38 30" src="https://user-images.githubusercontent.com/20328243/179279196-e093a8c2-c179-46a7-8820-df7798872ff2.png">

Cache TTL Setting: 
`@Configuration
class RedisConfig {
    @Bean
    fun redisCacheManagerBuilderCustomizer(): RedisCacheManagerBuilderCustomizer {
        return RedisCacheManagerBuilderCustomizer { builder: RedisCacheManagerBuilder ->
            configurationMap["bucket4j"] = RedisCacheConfiguration.defaultCacheConfig()
                .entryTtl(Duration.ofHours(48))
            builder.withInitialCacheConfigurations(configurationMap)
        }
    }
}`

**Comment by leter** [comment]
can the author provide a configuration item in yml to set the keys ttl? because  if you set  ip address  as key ,household ip addres will often change, when ip changed the previous ip were untouchable and finally turn to diry data.

**Comment by JakobStadlhuber** [comment]
I tried everything with `spring.cache.redis.time-to-live=100` and also programmaticly I can't configure the TTL. I also use Redis for Caching the TTL settings are no problem the problem only exists with bucket4j. The problem also exists without `bucket4j.filters[0].rate-limits[0].expression=getRemoteAddr()`

**Comment by JakobStadlhuber** [comment]
The problem still exists when setting the default ttl globally, it just don't use it.

**Comment by MarcGiffing** [comment]
@ttulka You've added the Redis Support in this project and also add Support for Jedis in the Bucket4j project https://github.com/bucket4j/bucket4j/pull/275. I haven't used Redis yet and I would be very thankful for your help. I even don't understand the real problem.

**Comment by MarcGiffing** [comment]
Oh, I've found this one:
https://github.com/bucket4j/bucket4j/issues/279#issuecomment-1194290148

**Comment by ttulka** [comment]
> Oh, I've found this one: [bucket4j/bucket4j#279 (comment)](https://github.com/bucket4j/bucket4j/issues/279#issuecomment-1194290148)

Yes, I added Redis support to bucket4j, so the whole `com.giffing.bucket4j.spring.boot.starter.config.cache.redis` is obsolete. 
A clash of those two implementations could simply cause the problem. I would recommend removing it from the starter whatsoever.
