### ISSUE TITLE
More examples needed for different rate limiters by CRUD API

### ISSUE THREAD

**Issue by adithya217** [MarcGiffing/bucket4j-spring-boot-starter#121]
The current examples on how to assign different buckets/bandwidth to different APIs is not clear.

For example:
Supposed I had to apply different rate-limits to different APIs:
Rate Limit A1 for POST /v1/test API;
Rate Limit B1 for PUT /v1/test API;
Rate Limit C1 for GET /v1/test API;

Rate Limit A2 for POST /v2/test API;
Rate Limit B2 for PUT /v2/test API;
Rate Limit C2 for GET /v2/test API;

The current documentation is not clear on the property combinations required to achieve this. It would great if these examples are also provided.

**Comment by MarcGiffing** [comment]
As an alternative for the execute-condition which uses the Spring Expression Language it will be possible to configure independent predicates. The configuration is inspired by the Spring Cloud Gateway.

Configuration example:
```properties
bucket4j.filters[0].rate-limits[0].execute-predicates[0]=PATH=/hello # Only executes if the path is '/hello'
bucket4j.filters[0].rate-limits[0].execute-predicates[1]=METHOD=GET # AND only executes if the HTTP Method is 'GET'
bucket4j.filters[0].rate-limits[0].execute-predicates[2]=QUERY=HELLO # AND only executes if the Query Paramter HELLO exists.
```

It will be also possible to provide you own predicates:
[CustomQueryExecutePredicate](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/master/examples/caffeine/src/main/java/com/giffing/bucket4j/spring/boot/starter/examples/caffeine/CustomQueryExecutePredicate.java)
```properties
bucket4j.filters[0].rate-limits[0].execute-predicates[0]=CUSTOM-QUERY=huhu
```

Its only a draft. Any feedback is welcome. Any ideas for default predicates?
