### ISSUE TITLE
Filters registered after ServletRequestFilter are not being called when limit is reached

### ISSUE THREAD

**Issue by Joaonic** [MarcGiffing/bucket4j-spring-boot-starter#123]
Hi guys, I have a need to make a new handler after rate limit reached (response status 429 on filter chain), and it cannot be done chaining the [ServletRequestFilter](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/master/bucket4j-spring-boot-starter/src/main/java/com/giffing/bucket4j/spring/boot/starter/filter/servlet/ServletRequestFilter.java).

Filters registered after [ServletRequestFilter](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/master/bucket4j-spring-boot-starter/src/main/java/com/giffing/bucket4j/spring/boot/starter/filter/servlet/ServletRequestFilter.java) are not being called when limit is reached. 

As 

```java
if (!probe.isConsumed()) {
    allConsumed = false;
    this.handleHttpResponseOnRateLimiting(response, probe);
    break;          
}
```
And the condition required to call next filter on chain is

```java
if (allConsumed) {
    if (remainingLimit != null && Boolean.FALSE.equals(this.filterConfig.getHideHttpResponseHeaders())) {
        response.setHeader("X-Rate-Limit-Remaining", "" + remainingLimit);
    }
    
    filterChain.doFilter(request, response);
}
```

Any workaround to customize handler after rate limit reached ?

**Comment by MarcGiffing** [comment]
You have to create a Filter that is executed Before the ServletRequestFilter. Than you put your logic after the doFilter of the chain and check for the HTTP-Status of the response.

```java
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class YourCustomFilter extends OncePerRequestFilter {

	@Override
	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
			throws ServletException, IOException {
		
		filterChain.doFilter(request, response);
		System.out.println("BEFORE " + response.getStatus());
		
	}

}
```
