### ISSUE TITLE
Dynamically update rate limit bandwidths

### ISSUE THREAD

**Issue by nayakkiranraj** [MarcGiffing/bucket4j-spring-boot-starter#124]
Currently we can initialize rate limit bandwidths from spring boot application.properties. However, we want to update the rate limit bandwidt using a rest endpoint and expect the limit gets applied without restarting the application. Eg. increase the rate limit from "100 requests in 10 minutes" to "200 requests in 10 minutes" **without restarting the application**.

Currently it is not allowed by just injecting the 'Bucket4JBootProperties' as 'bucket4JServletRequestFilterX' gets initialized when spring beans are loaded and there is no cleaner way of updating the 'ServletRequestFilter.filterConfig'.

Even if we try to destroy and recreate 'bucket4JServletRequestFilterX' & 'Bucket4JAutoConfigurationServletFilter' beans after updating bandwidth in 'Bucket4JBootProperties', updated bandwidths doesn't get updated as 'final ConfigurationBuilder' instance in 'Bucket4JBaseConfiguration.buildFilterConfig()' doesn't get updated which is actually used for check.

Your help is much appreciated to achieve updating bandwidths on the fly without restarting the application.

**Comment by MarcGiffing** [comment]
How do you want to refresh the properties? With Spring Boot Actuator and the /refresh endpoint? Its not possible to add/remove the ServletFilters so we need a unique name to identify already added filters to update the configuration dynamically and replace the FilterConfiguration inside of the ServletRequestFilter. 

My thought is to Listen for Spring Clouds RefreshEvent and create a new FilterConfiguration for the ServletRequestFilter based on the property information wich matches the new "name" property to identify the filter.

**Comment by nayakkiranraj** [comment]
Thanks for considering this feature request. It will be good if we can update FilterConfiguration programmatically in a custom endpoint (by injecting FilterConfiguration) and then manually refresh ServletRequestFilter using new "name" property. This would be helpful if Spring Cloud is not involved.

**Comment by nayakkiranraj** [comment]
Upgrading to 0.9.1 for this feature will force us to move to spring boot 3 and java 17+, which will be a difficult move for us. Can we retrofit this fix on 0.8.x as well ? 

We are still on 0.6.1 and moving to 0.8.x should not be a big change ? Also, we are on spring boot 2.6.7 and java 17

**Comment by MarcGiffing** [comment]
Thanks to [Edwin9292], this will be fixed in https://github.com/MarcGiffing/bucket4j-spring-boot-starter/issues/124
