### ISSUE TITLE
Redis bucket4j cache is not evicted with @CacheEvict

### ISSUE THREAD

**Issue by dmitry-naumovich** [MarcGiffing/bucket4j-spring-boot-starter#126]
Hello, I'm using bucket4j and your starter to protect API from DDoS. I'm using `@CacheEvict` with `@Scheduled` so that each time when the application starts, the cache with this name must be evicted, and then it's done on periodical basis by schedule. But I have noticed that evicting doesn't work and even if I change the bandwith in my `application.yml` file, the same old values for bandwith are preserved which means that the old values are still in cache and they are not evicted so the new value could be inserted into cache.

Here's my Redis Configuration:
```
public class RedisConfig {

    @Bean
    public CacheManager cacheManager(RedisConnectionFactory connectionFactory) {
        return RedisCacheManager.RedisCacheManagerBuilder
                .fromConnectionFactory(connectionFactory)
                .initialCacheNames(new HashSet<>("apiRequestsThrottlingCache"))
                .build();
    }

    @Bean
    public RedisCacheConfiguration cacheConfiguration() {
        return RedisCacheConfiguration.defaultCacheConfig()
//                .entryTtl(Duration.ofMinutes(1)) // doesn't help anyway
                .serializeKeysWith(fromSerializer(new Jackson2JsonRedisSerializer<>(String.class)))
                .serializeValuesWith(fromSerializer(new GenericJackson2JsonRedisSerializer()));
    }

    @CacheEvict(allEntries = true, cacheNames = "apiRequestsThrottlingCache")
    @Scheduled(fixedDelay = 60 * 60 * 1000)
    public void apiRequestsThrottlingCacheEvict() { }
}
```

And this is my Here's my bucket4j configuration:
```
bucket4j:
  filters:
    - cache-name: apiRequestsThrottlingCache
      url: /api/first.*
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
```

So, if I change the capacity from 10 to another value and re-start the application, I anyway can't send more than 10 requests and `X-Rate-Limit-Remaining` header still has value 9 after first request.

I also have such config for other functionality with `@Cacheable`, so '@CacheEvict' works.

I'm limited to Java 8 and Spring Boot 2.6.1 so I'm using bucket4j-spring-boot-starter of version 0.6.1 and bucket4j-core with bucket4j-redis of version 7.6.0.

**Comment by ayoubAnbara** [comment]
Hi @dmitry-naumovich 
I find a difficulty when I tried to integrate Redis, could you please share with us a source code of a demo that demonstrate how to integrate bucket4j with Redis.

**Comment by MarcGiffing** [comment]
See https://github.com/MarcGiffing/bucket4j-spring-boot-starter/issues/202 dynamically update rate limits
