### ISSUE TITLE
spring-configuration-metadata.json is not generated since version 0.8.0-RC1

### ISSUE THREAD

**Issue by Kirikx** [MarcGiffing/bucket4j-spring-boot-starter#140]
Most likely, the metadata stopped being generated after the Lombok project was added to pom.xml (bucket4j-spring-boot-starter-context). Perhaps you should think about adding it manually, as it reduces the usability of the configuration in the IDE.
More details can be found in this issue https://github.com/spring-projects/sts4/issues/780

https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/376a48f32315a27cac76611a349866859c43b78e/bucket4j-spring-boot-starter-context/pom.xml#L41

**Comment by Kirikx** [comment]
The simplest solution that works is to add processor annotation processing explicitly. But I don't like the idea of ​​having to substitute the parent spring version explicitly. Thinking about a way to specify it transitively
<img width="797" alt="Снимок экрана 2023-03-01 в 23 25 46" src="https://user-images.githubusercontent.com/24649745/222258269-51f428c9-a1c3-4714-b2ce-c7457bb1357e.png">

**Comment by MarcGiffing** [comment]
Thank you for the ticket! I've removed the maven-compiler-plugin. It look like that it's not necessary. I've also added the maven enforcer plugin to check that the file is generated.

**Comment by MarcGiffing** [comment]
Please try RC2. I still have to update version 0.8.x

**Comment by Kirikx** [comment]
Yes, metadata is back in version 0.9.0-RC2. Thank you!
