### ISSUE TITLE
ZuulRateLimitFilter behaves differently than ServletRateLimitFilter

### ISSUE THREAD

**Issue by JeffQuandt** [MarcGiffing/bucket4j-spring-boot-starter#15]
`ZuulRateLimitFilter` only tries the first filter that matches by URL, even if that filter is skipped due to a `skipCondition` or `executeCondition`.

**Comment by MarcGiffing** [comment]
@JeffQuandt can you add the gradle plugin which should be used to execute the test?

**Comment by JeffQuandt** [comment]
Sure. See #16
