### ISSUE TITLE
metrics not showing up

### ISSUE THREAD

**Issue by KammererTob** [MarcGiffing/bucket4j-spring-boot-starter#191]
Hi,

i currently have the issue that the default metrics are not showing up on the endpoints (neither in "/actuator/metrics", nor in "/actuator/promotheus"). I have confirmed that:
- The rate limiting is working
- Bucket4jMetricHandler.handle is called and `Metric.counter(...).increment(...)` is also executed.

I am a bit lost on what i might be doing wrong, or if this is a bug. Here is my pom.xml:
```
<dependency>
   <groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
   <artifactId>bucket4j-spring-boot-starter</artifactId>
   <version>0.8.1</version>
</dependency>

<dependency>
   <groupId>io.micrometer</groupId>
   <artifactId>micrometer-registry-prometheus</artifactId>
</dependency>

<dependency>
   <groupId>org.ehcache</groupId>
   <artifactId>ehcache</artifactId>
   <version>3.10.8</version>
</dependency>
```

and this is my config:
```
management.endpoints.enabled-by-default=false
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=*

bucket4j.enabled=true
bucket4j.filters[0].cache-name=buckets
bucket4j.filters[0].strategy=first
bucket4j.filters[0].filter-method=servlet
bucket4j.filters[0].url=.*
bucket4j.filters[0].filter-order=1000
bucket4j.filters[0].rate-limits[0].cache-key=@rateLimitService.getRateLimitCacheKey()
bucket4j.filters[0].rate-limits[0].skip-condition=@rateLimitService.skipRateLimit()
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=5
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=10
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=seconds
```

Any help is greatly appreciated.

**Comment by MarcGiffing** [comment]
Can you provide a reproducible example project? I've updated the ehcache example and here is a screenshot of the prometheus endpoint:

![image](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/assets/3609928/76f867e8-05a3-404e-a4f0-eb021117e76f)

**Comment by MarcGiffing** [comment]
If anyone has the same problem please open a new issue with an example project.
