### ISSUE TITLE
Is 0.10.0 published?

### ISSUE THREAD

**Issue by ross-paypay** [MarcGiffing/bucket4j-spring-boot-starter#199]
In the README, 0.10.0 is suggested for SpringBoot 3.1
However I do not see 0.10.x in the [maven repository](https://mvnrepository.com/artifact/com.giffing.bucket4j.spring.boot.starter/bucket4j-spring-boot-starter)

**Comment by MarcGiffing** [comment]
Some minutes ago. Should be available in a couple of hours
