### ISSUE TITLE
How to add more than 10 filters?

### ISSUE THREAD

**Issue by letientai299** [MarcGiffing/bucket4j-spring-boot-starter#20]
We can define more than 10 filters in yml, and all of them are read correctly via Spring `@ConfigurationProperties`, but filter with index more than 10 can't be loaded. The number is hard coded as `zuulFilter*` and `ConfigCondition*` in `Bucket4JAutoConfigurationZuul`. 

The same situation problem will happen with servlet filter. Also, this gotcha is not documented anywhere.

I'm thinking about dynamically build `ZuulFilter` in `@PostConstruct` method or in a `@EventListener` method. Not sure which is better, but I believe we can have as much filter as we need.

One more question, are there any problem (regards performance, zuul limitations, ...) that we should consider before adding many rate limit filters?

**Comment by MarcGiffing** [comment]
I've tried to register the filter in various ways but without luck. Manually registered filters beans are not correctly detected. I'll give it another try the next days...

I can only add more hard coded filters as a workaround and throw an exception if the limit reached.
I thought that one don't need that much filters but it seems that it was a fallacy.

**Comment by MarcGiffing** [comment]
> One more question, are there any problem (regards performance, zuul limitations, ...) that we should consider before adding many rate limit filters?

Maybe I should register only one filter and handle the whole configuration there(?).

Is it an option to register multiple urls in one filter? Zuul uses 'return requestURI.matches(filterConfig.getUrl());' so you can use a regular expression for multiple urls.


> I'm thinking about dynamically build ZuulFilter in @PostConstruct method or in a @EventListener method. Not sure which is better, but I believe we can have as much filter as we need.

If you have a working example where a filter is registered programatically (without @Bean/@Component)...

**Comment by letientai299** [comment]
I'll try and get back to you with an example.
