### ISSUE TITLE
Extend `FilterMehod` enum for custom filters (like JMS)

### ISSUE THREAD

**Issue by marceloverdijk** [MarcGiffing/bucket4j-spring-boot-starter#216]
Hi Marc,

We are using your starter to rate-limit a REST API and the configuration options the starter provides are really useful.

But now we also had a requirement to rate-limit JMS endpoints in the same way.
We created a `Bucket4JAutoConfigurationJmsFilter` similar as the `Bucket4JAutoConfigurationServletFilter`.

Our `Bucket4JAutoConfigurationJmsFilter` also extends `Bucket4JBaseConfiguration<jakarta.jms.Message>`  but as you can see we use the JMS `Message` type instead of `HttpServletRequest` which works well for us.

Our `customize` method looks like:

```
    @Override
    public void customize(ConfigurableServletWebServerFactory factory) {
        var filterCount = new AtomicInteger(0);
        properties.getFilters().stream()
                .filter(filter -> StringUtils.hasText(filter.getUrl()) && filter.getFilterMethod().equals(FilterMethod.WEBFLUX))
                .forEach(filter -> {
                    addDefaultMetricTags(properties, filter);
                    filterCount.incrementAndGet();
                    var filterConfig = buildFilterConfig(filter, cacheResolver.resolve(filter.getCacheName()), servletFilterExpressionParser, beanFactory);

                    servletConfigurationHolder.addFilterConfiguration(filter);

                    context.registerBean("bucket4jJJmsFilter" + filterCount, Object.class, () -> new JmsRateLimiterFilter(filterConfig));
                    // log.info("create-jms-filter;{};{};{}", filterCount, filter.getCacheName(), filter.getUrl());
                });
    }
````

The only thing we had to do is abuse the `FilterMethod.WEBFLUX` to distinguish the type to be able to use both `SERVLET` and our JMS variant.
Luckily we are not using `WEBFLUX` so we choose that one for JMS.

Would it be possible to add a `OTHER` or `CUSTOM` (or perhaps `JMS`) value to the `FilterMethod` enum? Same as `GATEWAY` was added? Or simply use a `String` instead of an enum for more flexibility? This would allow users to add custom filters more easily without interfering with the out-of-the-box filters provided by your starter.

**Comment by MarcGiffing** [comment]
Hey, after "Dynamically updating rate limits #204" is merged I'll add JMS to the FilterMethod. But you're free to provide a PR :-) with a better and general solution.
