### ISSUE TITLE
bucket4j don't seems to limit requests

### ISSUE THREAD

**Issue by julianoborba** [MarcGiffing/bucket4j-spring-boot-starter#24]
Hello, I'm building a sample of usage for bucket4j in a controlled scenario for DDoS simulation and mitigation. However, I followed the README for bucket4j-spring-boot-starter, but didn't get your component to work in my project.

I'm trying to setup Zuul with bucket4j properties yml, everything is working except that the request to my REST service ins't being rate limited.

My confs below:

[application.yml](https://raw.githubusercontent.com/julianoborba/ddos-mitigation-with-bucket4j/master/zuul/src/main/resources/application.yml)

[ehcache.xml](https://raw.githubusercontent.com/julianoborba/ddos-mitigation-with-bucket4j/master/zuul/src/main/resources/ehcache.xml)

[pom.xml](https://raw.githubusercontent.com/julianoborba/ddos-mitigation-with-bucket4j/master/zuul/pom.xml)

Can someone provide a little tip of what I'm doing wrong?

Thank you in advance.

**Comment by MarcGiffing** [comment]
Did you add the EnableCaching annotation on your main class? Maybe I should add some logging information about the status and the configured filters...

**Comment by MarcGiffing** [comment]
You can also add 

> debug: true

 to your application.yml to see why the starter is not running.

**Comment by julianoborba** [comment]
@MarcGiffing 

EnableCaching annotation was missing, then I annotated my Zuul main class and now I can see ecache stuff and bucket4j being loaded with debug properties enabled:

```
   Bucket4JAutoConfigurationServletFilter matched:
      - @ConditionalOnClass found required classes 'javax.cache.Caching', 'org.springframework.cache.jcache.JCacheCacheManager'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
      - @ConditionalOnProperty (bucket4j.enabled) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: javax.cache.CacheManager; SearchStrategy: all) found bean 'jCacheCacheManager' (OnBeanCondition)

   Bucket4JAutoConfigurationZuul matched:
      - @ConditionalOnClass found required classes 'javax.cache.Caching', 'org.springframework.cache.jcache.JCacheCacheManager', 'com.netflix.zuul.ZuulFilter'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
      - @ConditionalOnProperty (bucket4j.enabled) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: javax.cache.CacheManager; SearchStrategy: all) found bean 'jCacheCacheManager' (OnBeanCondition)

   Bucket4JAutoConfigurationZuul#zuulFilter1 matched:
      - AllNestedConditions 2 matched 0 did not; NestedCondition on Bucket4JAutoConfigurationZuul.ConfigCondition1.OnServletFilter @ConditionalOnProperty (bucket4j.filters[0].filter-method=zuul) matched; NestedCondition on Bucket4JAutoConfigurationZuul.ConfigCondition1.OnEnabled @ConditionalOnProperty (bucket4j.filters[0].url) matched (Bucket4JAutoConfigurationZuul.ConfigCondition1)
```

I had to pay attention to URL in bucket4j filter properties since it matched the desired filter.

Now everything is working.

I agree with you that a log with info of the status of bucket4j would be helpful, but the Spring debug log seems to be fair enough for now.

And just a curiosity:

I had to set url: /ddos/someservice/verylazy (full path to limit the request of my resource) to get everything working.
Before, I was trying to use /ddos/someservice/* but it didn't take effect (no limit warning response).

There is something speficif about it?

Thank you.

**Comment by MarcGiffing** [comment]
```java 

@Override
	public boolean shouldFilter() {
		RequestContext currentContext = RequestContext.getCurrentContext();
		HttpServletRequest request = currentContext.getRequest();
		String requestURI = request.getRequestURI();
		return requestURI.matches(filterConfig.getUrl());
	}
```

The Zuul rate limit class uses the matches method which expects a regular expression. I think the * is specific for the HttpServletRequest configurations.(?)

**Comment by julianoborba** [comment]
@MarcGiffing 

Great!

I setted
```
url: "/ddos/someservice/[a-z]+"
```
And now I'm matching anything "inside" "/ddos/someservice/".

Thank you. We can close this issue as solved.

**Comment by MarcGiffing** [comment]
Its maybe better to use the regular expression dot . as a wildcard for any character.

I've created a new ticket for Spring Boots Actuator support to see the configured filters #25
