### ISSUE TITLE
Suggestion: Update documentation to use `cache-key` instead of the deprecated field `expression` inside rate-limit

### ISSUE THREAD

**Issue by franciscofeo** [MarcGiffing/bucket4j-spring-boot-starter#264]
Hello guys,

I started to use this dependency in my company's projects but in the beginning I was a little confused about the `expression` field, because in the versions 0.8 until 0.11 (I think) it was deprecated, but in the newer version this field was completely removed and replaced by `cache-key`. The docs available in the first page still use the old field name, do you think that is a good idea change the examples or at least put a mention about the new field name?

Tnx :)

**Comment by MarcGiffing** [comment]
I've updated the Release with the specific deprecated field. There was only the hint about an expression property.
https://github.com/MarcGiffing/bucket4j-spring-boot-starter/releases/tag/bucket4j-spring-boot-starter-parent-0.12.0

I've also updated the migration guide and the example in the Readme. Please tell me if I overlooked something.

**Comment by franciscofeo** [comment]
This is great @MarcGiffing!! Both the release and documentation were good and better explained now! I guess there are no places that are using `expression` incorrectly anymore :)
