### ISSUE TITLE
Logging of Expression Parsing

### ISSUE THREAD

**Issue by Noxaro** [MarcGiffing/bucket4j-spring-boot-starter#268]
Hi,

with the latest release we encountered some log spam on each incoming request regarding the expression parsing:

https://github.com/MarcGiffing/bucket4j-spring-boot-starter/compare/bucket4j-spring-boot-starter-parent-0.11.0...bucket4j-spring-boot-starter-parent-0.12.0#diff-590ef8ddf69ace47bff1b1b764c74f18403ada7a3311f350d8f503df690300c5R28

Is it expected that this logger is on info level? Maybe it should be Debug.
I've worked around this by setting the class logger to warn.

Best Regards
Noxaro

**Comment by MarcGiffing** [comment]
Sorry, my mistake. I'll release a new version
