### ISSUE TITLE
Infinispan support

### ISSUE THREAD

**Issue by jibbe** [MarcGiffing/bucket4j-spring-boot-starter#27]
Having problems getting the infinispan support going. Any pointers?

I've tried a lot of combinations without success. My current build.gradle has the following dependencies:
```
    compile ('com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter:0.1.2')
    compile ('com.github.vladimir-bukhtoyarov:bucket4j-infinispan:3.1.1')
    compile ('org.infinispan:infinispan-cloud')
    compile ('org.infinispan:infinispan-jcache')
```
Then in application.yml
```
  cache:
     jcache:
      config: classpath:infinispan.xml
```
But it throws an error:
`Caused by: java.lang.UnsupportedOperationException: The Cache provider org.infinispan.jcache.embedded.JCachingProvider is incompatible with Bucket4j,  use module bucket4j-infinispan directly`

From the bucket4j docs, it says to include bucket4j-infinispan.  This dependency wasn't added by the started, so I added that. But the JCacheManagerConfiguration seems to still be in use.

I'm a bit confused by all of this. Any help appreciated.

**Comment by MarcGiffing** [comment]
Can you try to remove the jcache dependency cause the bucket4j-infininspan doesn't use jcache due to the async support.

If this doesn't work please exclude the 'com.github.vladimir-bukhtoyarov:bucket4j-jcache' from the the 'com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter' dependency cause I'm still adding it as a default for backwards compatibility.

I'll update the documentation and try to provide a better auto configuration with propper exceptions.

**Comment by MarcGiffing** [comment]
I'm still working on the async support https://github.com/MarcGiffing/bucket4j-spring-boot-starter/issues/26. I'm not sure if you added the 'com.github.vladimir-bukhtoyarov:bucket4j-infinispan' for async support on purpose. Is the a JCache implementation? I think the async support with this starter makes only sense if you use Webflux

**Comment by jibbe** [comment]
If I didn't have the bucket-jcache there in an error:
**Parameter 0 of constructor in com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration required a bean of type 'javax.cache.CacheManager' that could not be found.**

Looking at the code a bit, it appeard that the JCacheBucket4jConfiguration was still be 'executed', I added this annotation to the class and it get's past that error. 
**@ConditionalOnMissingClass({ "org.infinispan.manager.CacheContainer" })**

I've validated the CacheContainer bean is present. But I haven't confirmed that this the InfinispanBucket4jCacheConfiguration is setting up.  The bucket4j filter isn't installing at this point, but no errors.

Yes, I added the bucket4j-infinispan dependency.

I played around where the spring:cache settings in application.yml, but not much luck. Using the following sets up a cache okay however form the application.yml:

```
infinispan:
  embedded:
    config-xml: infinispan.xml
```
But I'm not sure if this the correct way, all your demos use the spring:cache:... approach.

Not sure really how webflux fits in. Can you not use sync with infinispan?

**Comment by MarcGiffing** [comment]
Ah ok, I wan't aware that infinispan doesn't work with jcache. From the documentation:

https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/infinispan.md
Question: Bucket4j already supports JCache since version 1.2. Why it was needed to introduce direct support for Infinispan?
Answer: When you want to use Bucket4j together with Infinispan, you must always use bucket4j-infinispan module instead of bucket4j-jcache

I've to take soon a closer look at the infinispan module to provide a propper autoconfiguration...sorry.

**Comment by jibbe** [comment]
Infinispan works with jcache just fine, but not bucket4j. In getting it going I enabled jcache in infinispan to get pass the JCacheBucket4jConfiguration overriding issue originally.  I've tried with it enabled and not. I myself are not sure from bucket4j docs/code if it needs jcache or if it's using the native api. I need to look.

I'll keep debugging to see if I can see the problem tomorrow. I'm in PST timezone. I'm mostly just trying things as I'm not to familiar with either code projects.

Interestingly, hazelcast is meant to have the same issue. So I tried using that demo you have as a template for infinispan but no luck.

Thanks for your project!
And I can help with solving this/testing, up to my ability, haha.

**Comment by jibbe** [comment]
The reason I've been confused about the dependency is you see this jar dependency from gradle:

```
+--- com.github.vladimir-bukhtoyarov:bucket4j-infinispan:3.1.1
|    +--- com.github.vladimir-bukhtoyarov:bucket4j-core:3.1.1
|    \--- com.github.vladimir-bukhtoyarov:bucket4j-jcache:3.1.1
|         \--- com.github.vladimir-bukhtoyarov:bucket4j-core:3.1.
```

**Comment by MarcGiffing** [comment]
How can I instantiate the ReadWriteMap. How can I access it when using e.g. https://github.com/infinispan/infinispan-spring-boot?

**Comment by vladimir-bukhtoyarov** [comment]
> Why not using the org.infinispan.Cache? 

It does not provide functionality to execute EntryProcessors.

> How can I instantiate the ReadWriteMap. How can I access it when using e.g. https://github.com/infinispan/infinispan-spring-boot? 

It is better to address this question to Infinispan developers.

**Comment by jibbe** [comment]
I tried using the springboot jcache approach in the application.yml:
```
spring:
  cache:
    jcache:
      config: classpath:infinispan.xml
```
But this didn't correctly setup my infinispan (using replicated cache in kubernetes envrionment).  The spring docs also mention use of this approach is 'basic' and the recommend approach is to the the infinspan spring boot support.
[https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-infinispan](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-infinispan)
Same issue if I use: `spring.cache.infinispan.config=infinispan.xml`

When I use the infinispan spring boot starter approach, using:
```
infinispan:
  embedded:
    config-xml: infinispan.xml
```
Then the same config starts up correctly. That config is:
```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:infinispan:config:9.2 http://infinispan.org/schemas/infinispan-config-9.2.xsd"
    xmlns="urn:infinispan:config:9.2">
    
    <jgroups>
        <stack-file name="external-file" path="default-configs/default-jgroups-kubernetes.xml"/>
    </jgroups>

    <cache-container default-cache="bucket4j" statistics="true" name="ifinispan-container" >
        <transport stack="external-file" />
        <replicated-cache name="bucket4j" mode="SYNC" statistics="true" />
        
    </cache-container>
</infinispan>
```
Linking with the infinspan embedded starter, I can inject the cachemanager:
```
    @Autowired
    private EmbeddedCacheManager cacheManager;
```
Then I believe this code will create the map correctly based on @vladimir-bukhtoyarov codes above. I tested that the function returns an map instance at runtime.
 ```
    private static ReadWriteMap toMap(EmbeddedCacheManager cm) {
        org.infinispan.Cache nativeCache = cm.getCache("bucket4j");
        FunctionalMapImpl functionalMap = FunctionalMapImpl.create(nativeCache.getAdvancedCache());
        return ReadWriteMapImpl.create(functionalMap);
    }
```
Support for the remotecachemaanger should work the same. But not sure if that is a valid requirement.

**Comment by MarcGiffing** [comment]
Thank you!
