### ISSUE TITLE
HazelcastSpringBucket4jCacheConfiguration support for SyncCacheResolver 

### ISSUE THREAD

**Issue by bryanxtong** [MarcGiffing/bucket4j-spring-boot-starter#292]
I have some problems as below

1. When using cache-to-use “ hazelcast-spring”, HazelcastSpringBucket4jCacheConfiguration should be updated to support SyncCacheResolver and should not be AsyncCacheResolver which will not work
  ` @Bean
    @ConditionalOnMissingBean(SyncCacheResolver.class)
    public SyncCacheResolver hazelcastCacheResolver() {
           #just for example as below
           return new HazelcastSyncCacheResolver(hazelcastInstance, false);
    } `
    

2. Make changes for Bucket4jCacheConfiguration to include IgniteBucket4jCacheConfiguration for support ignite async and change IgniteCacheResolver#isAsync() return true

3. Making Changes of the annotation @ConditionalOnCache("jcache-ignite") to @ConditionalOnCache("jcache-infinispan")  for InfinispanJCacheBucket4jConfiguration is more clear

**Comment by MarcGiffing** [comment]
Can you please review #304
