### ISSUE TITLE
Bucket 4j not running with boot 3.1.2 and bucket4j-spring-boot-starter 0.10.3

### ISSUE THREAD

**Issue by gangadharkasturi** [MarcGiffing/bucket4j-spring-boot-starter#361]
Bucket4j components are not running with boot 3.1.2 and bucket4j-spring-boot-starter 0.10.3 and JDK 17.
Cannot see the logs that the Bucket4JAutoConfigurationSpringCloudGatewayFilter filter has initialized and the rate limiter is not working.

But this example working fine: [] (https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/tree/master/bucket4j-spring-boot-starter-example-gateway)

My POM.XML:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.2</version>
		<relativePath />
	</parent>
	
	<groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
	<artifactId>bucket4j-spring-boot-starter-example-gateway</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<java.version>17</java.version>
		<spring-cloud.version>2022.0.3</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway</artifactId>
		</dependency>
		<dependency>
			<groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
			<artifactId>bucket4j-spring-boot-starter</artifactId>
			<version>0.10.3</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-hazelcast</artifactId>
			<version>7.6.0</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>`

Rest of the classes are same as the example link attached above.

Please help.

**Comment by gangadharkasturi** [comment]
pls help

**Comment by MarcGiffing** [comment]
Please use the latest version 0.12.8. Use the property debug=true and take a look at the Bucket4j autoconfiguration classes.

**Comment by gangadharkasturi** [comment]
My project has limitation to use boot 3.1.2 only.  As per the documentation it is recommended to use 0.10.x version with boot version 3.1.x.

Please help.

**Comment by MarcGiffing** [comment]
```
My project has limitation to use boot 3.1.2 only. As per the documentation it is recommended to use 0.10.x version with boot version 3.1.x.
``` 

Please give it a try. It should be backward compatible.

Bucket4JAutoConfigurationServletFilter this configuration is used in a Servlet environment. The Gateway Example uses Bucket4JAutoConfigurationSpringCloudGatewayFilter. It requires a AsyncCacheResolver.

**Comment by gangadharkasturi** [comment]
Issue resolved, Tried new versions with other required bucket4j dependency jars along with required cache configurations. Please update your documentation to have other two cache names hazelcast-spring and hazelcast-core.
Also when combined with this gateway, need to mandatorily include filter-method to WEBFLUX to register the filter with spring.
