### ISSUE TITLE
Upgrade to Bucket4j 4.5.0

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/bucket4j-spring-boot-starter#47]

**Comment by MarcGiffing** [comment]
Hmm...the last release was 4.4.1
https://search.maven.org/search?q=g:com.github.vladimir-bukhtoyarov%20AND%20a:bucket4j-core&core=gav

**Comment by tijanaa** [comment]
When can a 0.1.16 release be expected? There is a bug in a bucket4j version used in 0.1.15 with fixed refill interval (the nanosToWaitForRefill method is not calculating the remaining time correctly). I can see that bucket4j is upgraded in 0.1.16-SNAPSHOT and this bug is resolved.

**Comment by MarcGiffing** [comment]
Please use the 0.2.0 version
