### ISSUE TITLE
Add Spring Cloud Gateway support

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/bucket4j-spring-boot-starter#49]

**Comment by kendzikq** [comment]
hey,

Any progress on that ?
I have spring cloud gateway in the project which is reactive in the nature and that would be great to use your starter to protect the entire application.

thanks a lot for any update on this topic.

**Comment by MarcGiffing** [comment]
I thought there is already rate limiting support in the Spring Cloud Gateway project:
https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-requestratelimiter-gatewayfilter-factory

**Comment by kendzikq** [comment]
Yes, but rate limiter in Spring Cloud Gateway supports Redis and unfortunately they do not have a solution for hazelcast.

**Comment by MarcGiffing** [comment]
OK, the configuration is almost the same as Webflux. It works with my sample project. I'll commit the next days. Can I upgrade to the latest Hazelcast and Spring Boot version? There is a breaking change while upgrading to the latest Hazelcast version.

**Comment by kendzikq** [comment]
yes, thank you @MarcGiffing

**Comment by MarcGiffing** [comment]
Can you try it with the current master?

**Comment by MarcGiffing** [comment]
Please leave a comment if there is a problem or open a new ticket
