### ISSUE TITLE
Bucket4j not limiting requests

### ISSUE THREAD

**Issue by ninaHerpertz** [MarcGiffing/bucket4j-spring-boot-starter#50]
I am currently trying to configure a request limiter within my spring boot project and I am quite lost by now. I have made several attempts to get it to work but I failed so far. I have a multi module project with one application module which contains the app and the configuration and the sub modules contain several different services grouped by their functionality. I am trying to get the request limiting to work for one specific service. 

My pom.xml in the application module where the main and the config are located contains the following dependencies; 

```xml
        <dependency>
            <groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
            <artifactId>bucket4j-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>
```
This is my ehcache,xml which is located in the resource folder of my applcation module: 

```xml
<config xmlns='http://www.ehcache.org/v3'
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:jsr107="http://www.ehcache.org/v3/jsr107"
  xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd
							http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.0.xsd">
  <cache alias="buckets">
    <expiry>
      <tti unit="seconds">3600</tti>
    </expiry>
    <heap unit="entries">1000000</heap>
    <jsr107:mbeans enable-statistics="true"/>
  </cache>
</config>
```

My application configuration properties file looks like this:

```
bucket4j.enabled=true
bucket4j.filters[0].cache-name=buckets
bucket4j.filters[0].filter-method=servlet
bucket4j.filters[0].url=/rest/api/v1/fbm/send
bucket4j.filters[0].http-response-body={ "message": "Too many requests" }
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=5
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=2
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=minutes

spring.cache.jcache.config=classpath:ehcache.xml
```

This config is located in another module but is available in the classpath. I see during the startup that the properties are read by the application and no error is happening during startup. I can reach the service but the requests are not limited. I am not sure if it has something to do with my test setup, but I am using postman locally to call my local service. I also tried to create an unittest but it does not work as I am expecting it to. 

I am at a loss at the moment and not sure how to proceed. Perhaps you can help me with my issue. 

I have already tried to change the url back to ".*" but it does not work either. Additionally I have tried several other dependencies and more. We are using spring-cache for different other services. Could this be interfering in the overall functionality? 

Is there a good entry point for debugging (also during bootstrapping/startup)?  Thanks already!

**Comment by MarcGiffing** [comment]
You can set a debug flag to see which auto configuration are enabled:
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-replacing-auto-configuration

You can also add the Spring Boot Actuator dependency
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready
and look at the 'conditions' endpoint.

**Comment by ninaHerpertz** [comment]
As an additional note: EnableCaching is not directly set on the class containing the main method but on a class annotated with @Configuration also located in the application module. 

There I have also put the following code temporarily:

```java
@Bean
    public SyncCacheResolver syncCacheResolver() {
        return null;
    }

```

This resulted in an error during startup when it tried to create bucket4j components:
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.giffing.bucket4j.spring.boot.starter.config.servlet.Bucket4JAutoConfigurationServletFilter': Unsatisfied dependency expressed through field 'cacheResolver'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.giffing.bucket4j.spring.boot.starter.config.cache.SyncCacheResolver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

```

This tells me, it does try to load something and tries to configure bucket4j. So my config might be correct but something else is amiss I am currently not seeing. Perhaps this helps as well.

**Comment by MarcGiffing** [comment]
Please remove your SyncCacheResolver bean and take a look at the auto configuration described before. Maybe ehcache is not properly initialized with jcache.

The conditions for the Bucket4JAutoConfigurationServletFilter maybe matches cause you're defining the SynchCacheResolver bean.

You can also look at the examples projects:
https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/

**Comment by ninaHerpertz** [comment]
I just added this to see if it fails when it is giving null as it does. This was just a quick way to see if Bucket4j is trying to resolve its beans. 

How can I verify the other point you made? Is there a way to see if ehcache is properly initialized?

**Comment by MarcGiffing** [comment]
Look at my first post:
> You can set a debug flag to see which auto configuration are enabled:
> https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-replacing-auto-configuration
> 
> You can also add the Spring Boot Actuator dependency
> https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready
> and look at the 'conditions' endpoint.

**Comment by ninaHerpertz** [comment]
Hi, 

I found out, that my project has some dependencies to spring cache and some modules use this. I found this issue and I guess it relates to it: https://github.com/vladimir-bukhtoyarov/bucket4j/issues/93

So I think this ticket can be closed. We are not able to remove the spring cache dependencies from the project, which lead to my problems.

Thanks anyways for your help.
