### ISSUE TITLE
Infinispan Cache is not auto-configured

### ISSUE THREAD

**Issue by nikos** [MarcGiffing/bucket4j-spring-boot-starter#51]
It seems like spring boot is not able to pickup `InifinispanBucket4jCacheConfiguration `even though the infinispan libraries are all well in place in the classpath, added to my Maven pom.xml:

```
    <dependency>
      <groupId>org.infinispan</groupId>
      <artifactId>infinispan-spring-boot-starter-embedded</artifactId>
      <version>2.1.7.Final</version>
    </dependency>
```

**Comment by MarcGiffing** [comment]
Please open an issue if there is a problem. I can't test it. PR is welcome
