### ISSUE TITLE
Need an event handler to handle "Too many requests" event

### ISSUE THREAD

**Issue by Pritesh-Mhatre** [MarcGiffing/bucket4j-spring-boot-starter#62]
The requirement is to **notify the user about excessive requests being sent**. I looked at the servlet filter code and there is no event that is fired when we get an occurrence of a "Too many requests" event.

If not an event handler, then is there any alternative to achieve this?

**Comment by MarcGiffing** [comment]
Is Spring Boot Actuator an option?
https://github.com/MarcGiffing/bucket4j-spring-boot-starter/issues/42

**Comment by Pritesh-Mhatre** [comment]
Evaluated the actuator option, however I don't think that would be that best solution. Here are some of the points I thought about:

- First of all, completely understand the concern if we provide an event handler. As that function will be called many times and badly written handler can cause performance issues. But my point is that it is an optional feature (by default, there will not be any handler). So whoever using it, should read docs and understand the risks
- Actuator based approach is more for monitoring. I can notify clients, but that would mean...as a developer I would need to learn few more technologies and have those running in production environment (additional costs for hardware as well as maintenance)
- From design point of view, this feature should be provided by the API limit framework. Passing that responsibility to somewhere else is like adding more dependencies. **Actuator is good, it must remain** but it is more for monitoring than running custom logic when "Too many requests" event occurs.

**Comment by MarcGiffing** [comment]
Maybe its already possible. You can implement your own [MetricHandler](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/43c82224a53a0bda975c96572f7cf936e2a988ab/bucket4j-spring-boot-starter-context/src/main/java/com/giffing/bucket4j/spring/boot/starter/context/metrics/MetricHandler.java). For Spring Boot Actuator a 

The Spring Boot Actuator implementation can be found [here](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/a03d1666b71f46aedb9e7635fdf02347eddf3dde/bucket4j-spring-boot-starter/src/main/java/com/giffing/bucket4j/spring/boot/starter/config/metrics/actuator/Bucket4jMetricHandler.java)

**Comment by MarcGiffing** [comment]
If Spring Boot Actuator is present you must also disable the Bucket4J Spring Boot Actuator configuration.

[Bucket4jMetricsConfiguration](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/a03d1666b71f46aedb9e7635fdf02347eddf3dde/bucket4j-spring-boot-starter/src/main/java/com/giffing/bucket4j/spring/boot/starter/config/metrics/actuator/Bucket4jMetricsConfiguration.java)

**Comment by Pritesh-Mhatre** [comment]
Thank you, I will take a look. Appreciate your help.

**Comment by Pritesh-Mhatre** [comment]
I tried and managed to get it to work. Just found an issue described below along with solution to anyone who tries it.

1. Add following settings in application.properties
```
bucket4j.filters[0].metrics.enabled=false
bucket4j.filters[0].metrics.types=REJECTED_COUNTER
bucket4j.filters[0].metrics.tags[0].key=username
bucket4j.filters[0].metrics.tags[0].expression=getUserPrincipal().getPrincipal().getUsername()
```
2. Write your own implementation of `com.giffing.bucket4j.spring.boot.starter.context.metrics.MetricHandler`
3. Mark your bean as primary to avoid following error

**Error:**
This is due this TODO section [here](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/blob/1841838adb092eb78c4d9e01f3b3318a59231f6f/bucket4j-spring-boot-starter/src/main/java/com/giffing/bucket4j/spring/boot/starter/config/Bucket4JBaseConfiguration.java#L55).

NoUniqueBeanDefinitionException: No qualifying bean of type 'com.giffing.bucket4j.spring.boot.starter.context.metrics.MetricHandler' available: expected single matching bean but found 2: apiMetricHandler,dummyMetricHandler

**Solution:**
Annotate your metric handler with `org.springframework.context.annotation.Primary`.
