### ISSUE TITLE
Example with Caffeine is not working

### ISSUE THREAD

**Issue by dazito** [MarcGiffing/bucket4j-spring-boot-starter#64]
I was playing with Spring Boot, WebFlux, Caffeine and Bucket4j and I could not get it to work - to rate limit.

So I checked out https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/tree/master/bucket4j-spring-boot-starter-example-caffeine and it does not work as well - no rate limit is applied.

I would like to use Caffeine as the cache engine. Is there something wrong in the example or Caffeine it is not supported?

**Comment by MarcGiffing** [comment]
WebFlux is asynchrounous so we need an asynchrounous cache.
The supported asynchrounous caches are listed here:
https://github.com/vladimir-bukhtoyarov/bucket4j#supported-back-ends.

See also Bucket4JAutoConfigurationWebfluxFilter in this project. 

Maybe I'm wrong and I misinterpreted that...
