### ISSUE TITLE
Filter Order

### ISSUE THREAD

**Issue by SledgeHammer01** [MarcGiffing/bucket4j-spring-boot-starter#66]
I'm using Spring Authorization Server / @PreAuthorize for OAuth. I'm also using Logbook to log requests/responses.

If I use the starter on /throttle and there is no Authorization header, I'm still getting 429s when throttled. Based on the docs you have, shouldn't bucket4j.filters[0].filter-order=1 put it behind that filter? I've even tried putting Int.max and I still get 429 without being logged in.

I believe Logbook uses LOWEST_PRECEDENCE for its filter, so I put 2147483647 for the order, and that at least allowed logbook to capture the 429s when the authorization header is sent. Even with 2147483647, it seems like this is ahead of Spring Authorization Server somehow.

Seems like the issue is that you made your configuration class to have the highest precedence?

Any idea on how to set this up? I believe this is done by BearerTokenAuthenticationFilter.

EDIT: further debugging seems like its hitting after the bearer validation, but before the pre authorize filter.

**Comment by MarcGiffing** [comment]
#68
