### ISSUE TITLE
@EnableCaching is required in order for the starter to work

### ISSUE THREAD

**Issue by 4iner** [MarcGiffing/bucket4j-spring-boot-starter#67]
I saw this on a [stackoverflow comment](https://stackoverflow.com/questions/55890748/spring-boot-2-with-bucket4j-to-prevent-ddos-attacks/57235927#57235927?newreg=25b24ca6e70c4a3ebcef5b1cd6f04df4), but @EnableCaching needs to be added to the application class in order for this package to work, which isn't shown in the getting started documentation. If you could add that part, that would be help other people! Thanks

**Comment by leoaugustov** [comment]
Now you can close this issue.

**Comment by 4iner** [comment]
Cheers!
