### ISSUE TITLE
Tag with Actuator misinterpreted

### ISSUE THREAD

**Issue by elenoir** [MarcGiffing/bucket4j-spring-boot-starter#74]
Hi,

I just followed the documentation to add some custom tags on Actuator Metrics:

> bucket4j.filters[0].metrics.enabled=true
bucket4j.filters[0].metrics.types=CONSUMED_COUNTER,REJECTED_COUNTER
bucket4j.filters[0].metrics.tags[0].key=IP
bucket4j.filters[0].metrics.tags[0].expression=getRemoteAddr()
bucket4j.filters[0].metrics.tags[0].types=REJECTED_COUNTER
bucket4j.filters[0].metrics.tags[1].key=URL
bucket4j.filters[0].metrics.tags[1].expression=getRequestURI()
bucket4j.filters[0].metrics.tags[2].key=USERNAME
bucket4j.filters[0].metrics.tags[2].expression="@securityService.username() != null ? @securityService.username() : 'anonym'"

Everything is great for IP and URL but not for **bucket4j.filters[0].metrics.tags[2].expression** as it is not interpreted (I see `{"tag":"USERNAME","values":["@securityService.username() != null ? @securityService.username() : 'anonym'"]}` instead).

By removing the quotes it seems to work:

> bucket4j.filters[0].metrics.tags[2].expression=@securityService.username() != null ? @securityService.username() : 'anonym'

Should be a typo but just wanted to confirm with you.

Thanks for your work !

**Comment by MarcGiffing** [comment]
Thanks, your right!
