### ISSUE TITLE
Version 0.3.2 failing

### ISSUE THREAD

**Issue by SledgeHammer01** [MarcGiffing/bucket4j-spring-boot-starter#76]
0.2.0 was working fine. Tried upgrading to 0.3.2 and get:

Failed to collect dependencies at com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter:jar:0.3.2: Failed to read artifact descriptor for com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter:jar:0.3.2: Could not find artifact com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter-parent:pom:${revision} in central (https://repo1.maven.org/maven2/)

Seems to maybe have something to do with that ${revision} tag not getting resolved. In my .m2 directory for bucket4j-spring-boot-starter-parent, I have 0.2.0 and ${revision} folders.

bucket4j-spring-boot-starter 0.3.2 got download correctly.

**Comment by MarcGiffing** [comment]
Can you please try version 0.3.3?

**Comment by SledgeHammer01** [comment]
> Can you please try version 0.3.3?

0.3.3 works now, thanks.
