### ISSUE TITLE
Webflux filter not invoked

### ISSUE THREAD

**Issue by atsharp** [MarcGiffing/bucket4j-spring-boot-starter#80]
I'll readily admit that I'm most likely doing something dumb, but I can't for the life of me get rate limiting working in a vanilla WebFlux project.

I created a small project [here](https://github.com/atsharp/bucket4j-webflux-demo/blob/main/src/test/java/com/bucket4j/demo/DemoApplicationTests.java) and added [a test](https://github.com/atsharp/bucket4j-webflux-demo/blob/main/src/test/java/com/bucket4j/demo/DemoApplicationTests.java) which demonstrates the problem. The test executes an endpoint that should receive a `429` since I force the number of permits to 0, however, it returns 200 indicating it was not rate-limited. Likewise, I've confirmed that the autoconfiguration classes are loaded and a filter is created, but it's never invoked in the filter chain.

I believe the issue is that the autoconfigured webflux filters are somehow not being registered in the application context appropriately and are not considered in the filter chain. Even creating a delegate `WebFilter` for the `WebfluxWebFilter` works as expected, so that seems to imply there's some sort of lifecycle issue.

Any ideas what might be wrong? Only difference I can see between this demo project and the [example webflux project](https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/tree/master/bucket4j-spring-boot-starter-example-webflux) is that I'm using a newer version of spring-boot (2.4.5 vs 2.3.7) and this starter (0.4.0 vs 0.2.0 in the example), though I also tried using different versions of both of those libraries without success.

Thanks!

**Comment by MarcGiffing** [comment]
The problem is that your custom bean asyncCacheResoler and proxyManager you've configured is auto configured after the bucket4j starter.  I've tested it with the 0.3.3 bucket4j starter version.

Use debug: true in the yaml configuration file to see if the webflux bucket4j auto configuration is picked up.

```java
@Configuration
@AutoConfigureBefore(Bucket4JAutoConfigurationWebfluxFilter.class)
public class MockAsyncConfiguration {

	@Bean
	public AsyncCacheResolver asyncCacheResolver() {
		final AsyncCacheResolver cacheResolver = mock(AsyncCacheResolver.class);
		doReturn(proxyManager()).when(cacheResolver).resolve(any());
		return cacheResolver;
	}

	@Bean
	public ProxyManager<String> proxyManager() {
		final Bucket bucket = mock(Bucket.class);
		final AsyncBucket asyncBucket = mock(AsyncBucket.class);
		final ConsumptionProbe consumptionProbe = ConsumptionProbe.rejected(0, 5);
		doReturn(CompletableFuture.completedFuture(consumptionProbe)).when(asyncBucket).tryConsumeAndReturnRemaining(anyLong());
		doReturn(asyncBucket).when(bucket).asAsync();
		final ProxyManager<String> proxyManager = mock(ProxyManager.class);
		doReturn(Optional.of(bucket)).when(proxyManager).getProxy(any());
		doReturn(bucket).when(bucket).toListenable(any());
		doReturn(bucket).when(proxyManager).getProxy(any(), any(BucketConfiguration.class));
		return proxyManager;
	}
	
}
```

I've also adapted your test class a little bit:

```java
@RunWith(SpringRunner.class)
@Import(MockAsyncConfiguration.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class DemoApplicationTests {

	@Autowired
	private ApplicationContext context;
	
	private WebTestClient webTestClient;

    @BeforeEach
    public void setup() {
        this.webTestClient = WebTestClient
            .bindToApplicationContext(this.context)
            .configureClient()
            .build();
    }

	@Test
	void testRateLimiting() {
		webTestClient.get()
				.uri("/test-rate-limit")
				.exchange()
				.expectStatus()
				.isEqualTo(429);
	}

	@Configuration
	@EnableAutoConfiguration
	static class Config  {

		@RestController
		@RequestMapping
		public class TestController {

			@GetMapping("/test-rate-limit")
			public Mono<Void> getRateLimit() {
				return Mono.empty();
			}

		}

	}

}
```

**Comment by atsharp** [comment]
Hmm, I'm very confident that the auto-configuration is executing in the right order. Adding debugging to the same repo (without any of the suggested changes), I see the autoconfig is picked up as I expect:
```
  Bucket4JAutoConfigurationWebfluxFilter matched:
      - @ConditionalOnClass found required class 'org.springframework.web.server.WebFilter' (OnClassCondition)
      - @ConditionalOnProperty (bucket4j.enabled) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: com.giffing.bucket4j.spring.boot.starter.config.cache.AsyncCacheResolver; SearchStrategy: all) found bean 'asyncCacheResolver' (OnBeanCondition)
```

Further, I see the creation of the filter is logged:
```
2021-05-18 15:39:31.263  INFO 69768 --- [           main] w.Bucket4JAutoConfigurationWebfluxFilter : create-webflux-filter;1;buckets;.*
```

And per the test assertions, the filter appears to exist in the application context:
```
@Autowired	
private Collection<WebFilter> webFilters;
...
assertThat(webFilters)				
  .anyMatch(filter -> filter instanceof WebfluxWebFilter);
```

Weirdly, if I change the test to add:
```
this.webTestClient = WebTestClient
            .bindToApplicationContext(this.context)
            .configureClient()
            .build();
``` 

then the test passes...

However, without that addition, even incorporating the recommended configuration changes doesn't appear to resolve the issue, so I'm not sure it's an autoconfiguration or ordering problem.

Also, I changed the application to run it as a standalone application, and the filter doesn't appear to be executed (`mvn spring-boot:run`):

```
curl localhost:8080/test-rate-limit -vvv
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /test-rate-limit HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-length: 0
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

And from the application logs:
```
2021-05-18 15:45:54.242 DEBUG 70175 --- [ctor-http-nio-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : [704eb73e-1] HTTP GET "/test-rate-limit"
2021-05-18 15:45:54.258 DEBUG 70175 --- [ctor-http-nio-2] s.w.r.r.m.a.RequestMappingHandlerMapping : [704eb73e-1] Mapped to com.bucket4j.demo.DemoApplication$TestController#getRateLimit()
2021-05-18 15:45:54.271 DEBUG 70175 --- [ctor-http-nio-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : [704eb73e-1] Completed 200 OK
```

I wonder if the `.bindToApplicationContext(this.context)` in the `WebTestClient` is forcing the application context to refresh the filters in a way that normally they wouldn't be?

**Comment by MarcGiffing** [comment]
OK, it seems that the problem is the missing spring-boot-starter-actuator dependency. The test should pass if you add it. The strange thing that the  Bucket4JAutoConfigurationWebfluxFilter is listed in the positive configurations. It's maybe due to the import statement @Import(value = { SpringBootActuatorConfig.class }). Thanks you, its a really big issue.
