### ISSUE TITLE
Add Spring Cloud Gateway support in Discovery Locator mode

### ISSUE THREAD

**Issue by tandser** [MarcGiffing/bucket4j-spring-boot-starter#91]
In my microservice architecture, I use a gateway in locator mode to create routes based on services registered in Netflix Eureka Discovery. In this case bucket4j-spring-boot-starter in gateway mode does not work as expected.

Thanks for any help.

**Comment by MarcGiffing** [comment]
What do you expect? Does the rate limit not happen?

**Comment by MarcGiffing** [comment]
I've created a sample project for Spring Cloud Gateway:
https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/tree/master/bucket4j-spring-boot-starter-example-gateway
