### ISSUE TITLE
Using 'X-FORWARDED-FOR' as rate limit expression

### ISSUE THREAD

**Issue by rainerknabenbauer** [MarcGiffing/bucket4j-spring-boot-starter#97]
I'm using Spring Reactive.

My application is behind a load balancer so calling `getRemoteAddress()` results in getting the IP of the load balancer instead of the application IP. To get the application IP I need to access the `ServerHttpRequest` header `X-FORWARDED-FOR`.

Is there an easy way to achieve this through config? If so, it would be sweet to have this in the README as well as I guess this is quite a common use case.

Thank you in advance!

**Comment by rainerknabenbauer** [comment]
So this is what worked for me:

`bucket4j:
  enabled: true
  filters:
    - metrics:
        types:
          - consumed-counter
          - rejected-counter
    - cache-name: buckets
      filter-method: webflux
      url: .*
      filter-order: 1
      rate-limits:
        - bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
          expression: "getHeaders()['X-FORWARDED-FOR']"`

`@Test
    fun `SUCCESSFULLY rate by X-FORWARDED-FOR header`() {
        // arrange
       val endpoint = "/api/someendpoint"

        // act
        WebTestClient
            .bindToApplicationContext(context)
            .configureClient()
            .defaultHeader("X-FORWARDED-FOR", "1.1.1.1")
            .build()
            .get()
            .uri(endpoint)
            .exchange()
            .expectStatus().isOk
            .expectHeader().valueEquals("X-Rate-Limit-Remaining", "0")

        WebTestClient
            .bindToApplicationContext(context)
            .configureClient()
            .defaultHeader("X-FORWARDED-FOR", "1.1.1.2")
            .build()
            .get()
            .uri(endpoint)
            .exchange()
            .expectStatus().isOk
            .expectHeader().valueEquals("X-Rate-Limit-Remaining", "0")

        WebTestClient
            .bindToApplicationContext(context)
            .configureClient()
            .defaultHeader("X-FORWARDED-FOR", "1.1.1.1")
            .build()
            .get()
            .uri(endpoint)
            .exchange()
            .expectStatus().isEqualTo(HttpStatus.TOO_MANY_REQUESTS)
            .expectBody().jsonPath("error", "Too many requests!")

        // assert

    }`

**Comment by JakobStadlhuber** [comment]
Does not work with servlet because getHeaders() can't be found.
